server:
  port: 8081
spring:
  application:
    name: first-server

  output:
    ansi:
      enabled: always


# Custom
second:
  server:
    prefix: second-server


### Eureka Client
#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka