server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/

spring:
  application:
    name: discovery-service
  main:
    web-application-type: reactive