server:
  port: 8080

spring:
  application:
    name: gateway-service
  profiles:
    active:
      dev
  cloud:
    gateway:
      routes:
        - id: first_route
          uri: http://localhost:8081
          predicates:
            - Path=/first/**
          filters:
            - RewritePath=/first/(?<segment>.*), /$\{segment}
        - id: second_route
          uri: http://localhost:8082
          predicates:
            - Path=/second/**
          filters:
            - RewritePath=/second/(?<segment>.*), /$\{segment}
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600